### ISSUE TITLE
A version of `push` that overrides the oldest element if full

### ISSUE THREAD

**Issue by walfie** [agerasev/ringbuf#5]
I have a use-case where I have a list of incoming events and want to retain the latest `n` items -- the producer pushes elements one by one, but the consumer will always iterate or fetch the full list without ever calling `pop`.

I'd like to know if there's a way for the producer to continue pushing items to the buffer, discarding old items if the buffer is full. Currently it seems the only way to do this is to have some coordination between the producer and consumer (check if `is_full` and then have the consumer `pop`, then the producer can `push`).

Not sure whether this fits with the design of this library, but is it feasible to have a version of `push` that overrides the oldest element if the buffer is full (or some other recommended approach)? On the consumer side, I'm not too concerned with receiving the items in the proper order, if that matters.

**Comment by agerasev** [comment]
If I understand you correctly, you suggest to introduce a method of a `Producer` that always succeed even if there is no free space in a ring buffer discarding latest elements in such case?

If so I'm afraid that this functionality would make this implementation of ring buffer non-SPSC because producer effectively becomes a consumer at the same time as it should be able to fetch and drop elements from the head of the buffer as well as appending new elements to the tail. In my opinion, making a buffer to be SPMC (or even MPMC) while keeping it non-blocking is of great effort and will require significant complication of ring buffer structure and algorithms. But if I'm wrong and you can provide an easy implementation of the proposed functionality that doesn't break the current one, I would be very glad to add it to the crate.

By the way, if you don't need your ring buffer to be non-blocking then you can easily make it MPMC by sharing access to producer and consumer by `Mutex<Arc<...>>` and after that you can use the technique you described above:
> check if `is_full` and then have the consumer `pop`, then the producer can `push`

**Comment by walfie** [comment]
no problem! Currently I'm just using the [`circular-queue`](https://github.com/YaLTeR/circular-queue) crate (wrapped with an `RwLock`, since it's blocking). I'm not too familiar with writing non-blocking algorithms in general, so I wasn't sure if it was feasible for this crate. It sounds like it would be complicated to add, so I'll just continue using the `RwLock` approach. Thanks!
